## Project Planning Stage (Individual)
#### Peter Wojnicki | 78625613 | Group 9 | Section 008

### <u>(1) Data Description:</u>

<center><b>Table 1.</b> Overview of Data with Number of Columns and Observations</center>

| Source File Name | Number of Columns | Total Number of Observations |
|:-:|:-:|:-:|
|players.csv| 7 | 196 |
|sessions.csv| 5 | 1535 | 

#### **Players Dataset**

**experience (chr):** "Amateur", "Beginner", "Regular", "Pro", "Veteran" assigned based on experience.

**subscribe (lgl):** "True" or "False" if subscribed.

**hashedEmail (chr):** Hashed Email of player.

**played_hours (dbl):** Number of hours played.

**name (chr):** Name of player.

**gender (chr):** "Female" or "Male" for gender of player.

**Age (dbl):** Age of player.

#### Potential Issues:
- experience is self-declared and might have some bias
- joining players with sessions 

#### **Sessions Dataset**

**hashedEmail (chr):** Hashed Email of player.

**start_time (chr):** Start time of session in format of DAY/MONTH/YEAR HOUR:MINUTE.

**end_time (chr):** End time of session in format of DAY/MONTH/YEAR HOUR:MINUTE.

**original_start_time (dbl):** Start time recorded in UNIX time (milliseconds).

**original_end_time (dbl):** End time recorded in UNIX time (milliseconds).

#### Potential Issues:
- start_time and end_time are dates and times that both need to be tidied
- original_start_time and original_end_time are in milliseconds

### <u>(2) Questions:</u>

I hope to address demand forecasting and try to use this data to predict highest demand periods.

### <u>(3) Exploratory Data Analysis and Visualization</u>

<center><b>Table 2.</b> Summary statistics for variables of interest</center>

| Variable Name | Mean | Median | Minimum | Maximum | Number of Observations |
|:-:|:-:|:-:|:-:|:-:|:-:|
|Player Age (years) | 21.14 | 19 | 9 | 58 | 196 |
|Played Hours (hours) | 5.85 | 0.1 | 0 | 223.1 | 196 |
|Elapsed Session Time (minutes) | 50.86 | 30 | 3 | 259 | 1535 |

In [1]:
### Run this cell before continuing.
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

#### Read the Datasets from URLs

In [2]:
players_data <- read_csv("https://raw.githubusercontent.com/wojpc/wojpc-dsci100-project-008-09/85fbc982690237a92b10d714a1b540644c562325/data/players.csv")
sessions_data <- read_csv("https://raw.githubusercontent.com/wojpc/wojpc-dsci100-project-008-09/85fbc982690237a92b10d714a1b540644c562325/data/sessions.csv")

Rows: 196 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): experience, hashedEmail, name, gender
dbl (2): played_hours, Age
lgl (1): subscribe

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1535 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): hashedEmail, start_time, end_time
dbl (2): original_start_time, original_end_time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

#### Number of Columns and Preview Data

In [3]:
nrow(players_data)
nrow(sessions_data)

head(players_data)
head(sessions_data)

[1] 196

[1] 1535

  experience subscribe
1 Pro         TRUE
2 Veteran     TRUE
3 Veteran    FALSE
4 Amateur     TRUE
5 Regular     TRUE
6 Amateur     TRUE
  hashedEmail                                                      played_hours
1 f6daba428a5e19a3d47574858c13550499be23603422e6a0ee9728f8b53e192d 30.3
2 f3c813577c458ba0dfef80996f8f32c93b6e8af1fa939732842f2312358a88e9  3.8
3 b674dd7ee0d24096d1c019615ce4d12b20fcbff12d79d3c5a9d2118eb7ccbb28  0.0
4 23fe711e0e3b77f1da7aa221ab1192afe21648d47d2b4fa7a5a659ff443a0eb5  0.7
5 7dc01f10bf20671ecfccdac23812b1b415acd42c2147cb0af4d48fcce2420f3e  0.1
6 f58aad5996a435f16b0284a3b267f973f9af99e7a89bee0430055a44fa92f977  0.0
  name      gender Age
1 Morgan    Male    9
2 Christian Male   17
3 Blake     Male   17
4 Flora     Female 21
5 Kylie     Male   21
6 Adrian    Female 17

  hashedEmail
1 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
2 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
3 f8f5477f5a2e53616ae37421b1c660b971192bd8ff77e3398304c7ae42581fdc
4 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
5 36d9cbb4c6bc0c1a6911436d2da0d09ec625e43e6552f575d4acc9cf487c4686
6 bfce39c89d6549f2bb94d8064d3ce69dc3d7e72b38f431d8aa0c4bf95ccee6bf
  start_time       end_time         original_start_time original_end_time
1 30/06/2024 18:12 30/06/2024 18:24 1.71977e+12         1.71977e+12
2 17/06/2024 23:33 17/06/2024 23:46 1.71867e+12         1.71867e+12
3 25/07/2024 17:34 25/07/2024 17:57 1.72193e+12         1.72193e+12
4 25/07/2024 03:22 25/07/2024 03:58 1.72188e+12         1.72188e+12
5 25/05/2024 16:01 25/05/2024 16:12 1.71665e+12         1.71665e+12
6 23/06/2024 15:08 23/06/2024 17:10 1.71916e+12         1.71916e+12

#### Summary Statistics for Quantitative Variables in Players Dataset

In [4]:
players_played_mean <- mean(players_data$played_hours, na.rm = TRUE)
players_played_min <- min(players_data$played_hours, na.rm = TRUE)
players_played_max <- max(players_data$played_hours, na.rm = TRUE)
players_played_med <- median(players_data$played_hours, na.rm = TRUE)

players_age_mean <- mean(players_data$Age, na.rm = TRUE)
players_age_min <- min(players_data$Age, na.rm = TRUE)
players_age_max <- max(players_data$Age, na.rm = TRUE)
players_age_med <- median(players_data$Age, na.rm = TRUE)

players_played_mean
players_played_med
players_played_min
players_played_max

players_age_mean
players_age_med
players_age_min
players_age_max

[1] 5.845918

[1] 0.1

[1] 0

[1] 223.1

[1] 21.13918

[1] 19

[1] 9

[1] 58

#### Grouping Qualitative Variables in Players Dataset

In [9]:
players_exp <- players_data |>
    group_by(experience) |>
    summarize(total_exp = n())

players_subbed <- players_data |>
    group_by(subscribe) |>
    summarize(total_exp = n())

players_gender <- players_data |>
    group_by(gender) |>
    summarize(total_exp = n())

#### Left Join Data on Hashed Email and Wrangle Time
A new column called session_time is added to show elapsed time of session and times are converted from strings to more usable data. Sessions data is now combined with player information. original_start_time and original_end_time were useless so I removed them to make the table tidier and less redundant.

In [17]:
sessions_players_joined <- sessions_data |>
  left_join(players_data, by = "hashedEmail")

sessions_players_elapsed <- sessions_players_joined |>
    mutate(end_time = as.POSIXct(end_time, format = "%d/%m/%Y %H:%M"),
           start_time =  as.POSIXct(start_time, format = "%d/%m/%Y %H:%M")) |>
    mutate(session_time_elapsed = as.numeric(end_time - start_time)) |>
    select(-hashedEmail, -original_start_time, -original_end_time)

nrow(sessions_players_elapsed)
head(sessions_players_elapsed)

[1] 1535

  start_time          end_time            experience subscribe played_hours
1 2024-06-30 18:12:00 2024-06-30 18:24:00 Regular    TRUE      223.1
2 2024-06-17 23:33:00 2024-06-17 23:46:00 Amateur    TRUE       53.9
3 2024-07-25 17:34:00 2024-07-25 17:57:00 Amateur    TRUE      150.0
4 2024-07-25 03:22:00 2024-07-25 03:58:00 Regular    TRUE      223.1
5 2024-05-25 16:01:00 2024-05-25 16:12:00 Amateur    TRUE       53.9
6 2024-06-23 15:08:00 2024-06-23 17:10:00 Regular    TRUE      223.1
  name    gender Age session_time_elapsed
1 Hiroshi Male   17   12
2 Alex    Male   17   13
3 Delara  Female 16   23
4 Hiroshi Male   17   36
5 Alex    Male   17   11
6 Hiroshi Male   17  122

#### Summary Statistics for Quantitative Variables in Joined Dataset

In [15]:
sessions_players_elapsed_mean <- mean(sessions_players_elapsed$session_time_elapsed, na.rm = TRUE)
sessions_players_elapsed_min <- min(sessions_players_elapsed$session_time_elapsed, na.rm = TRUE)
sessions_players_elapsed_max <- max(sessions_players_elapsed$session_time_elapsed, na.rm = TRUE)
sessions_players_elapsed_med <- median(sessions_players_elapsed$session_time_elapsed, na.rm = TRUE)

sessions_players_elapsed_mean
sessions_players_elapsed_med 
sessions_players_elapsed_min 
sessions_players_elapsed_max

[1] 50.85845

[1] 30

[1] 3

[1] 259